version: "3"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
    - 2181:2181
    logging: { driver: none }

  broker1:
    image: confluentinc/cp-kafka:5.3.1
    ports:
    - 9091:9091
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENERS: "INTERNAL://0.0.0.0:19091,PUBLIC://0.0.0.0:9091"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://broker1:19091,PUBLIC://localhost:9091"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,PUBLIC:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_NUM_PARTITIONS: 50
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_JMX_HOSTNAME: broker1
      KAFKA_JMX_PORT: 7000
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
    depends_on: [zookeeper]

  broker2:
    image: confluentinc/cp-kafka:5.3.1
    ports:
    - 9092:9092
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENERS: "INTERNAL://0.0.0.0:19092,PUBLIC://0.0.0.0:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://broker2:19092,PUBLIC://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,PUBLIC:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_NUM_PARTITIONS: 50
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_JMX_HOSTNAME: broker2
      KAFKA_JMX_PORT: 7000
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
    depends_on: [zookeeper]

  broker3:
    image: confluentinc/cp-kafka:5.3.1
    ports:
    - 9093:9093
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENERS: "INTERNAL://0.0.0.0:19093,PUBLIC://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://broker3:19093,PUBLIC://localhost:9093"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,PUBLIC:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_NUM_PARTITIONS: 50
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_JMX_HOSTNAME: broker3
      KAFKA_JMX_PORT: 7000
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
    depends_on: [zookeeper]

  # broker4:
  #   image: confluentinc/cp-kafka:5.3.1
  #   ports:
  #   - 9094:9094
  #   environment:
  #     KAFKA_BROKER_ID: 4
  #     KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
  #     KAFKA_LISTENERS: "INTERNAL://0.0.0.0:19094,PUBLIC://0.0.0.0:9094"
  #     KAFKA_ADVERTISED_LISTENERS: "INTERNAL://broker4:19094,PUBLIC://localhost:9094"
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,PUBLIC:PLAINTEXT"
  #     KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
  #     KAFKA_NUM_PARTITIONS: 1
  #     KAFKA_DEFAULT_REPLICATION_FACTOR: 3
  #     KAFKA_DELETE_TOPIC_ENABLE: "true"
  #     KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 1
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
  #     KAFKA_TRANSACTION_STATE_LOG_NUM_PARTITIONS: 50
  #     KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
  #     KAFKA_JMX_HOSTNAME: broker4
  #     KAFKA_JMX_PORT: 7000
  #     KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
  #   depends_on: [zookeeper]

  schema-registry:
    # build: ./schema-registry/
    image: confluentinc/cp-schema-registry:5.3.1
    hostname: schema-registry
    ports:
    - 8080:8080
    - 9021:9011
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8080"

      # SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "PLAINTEXT://broker1:19091,PLAINTEXT://broker2:19092,PLAINTEXT://broker3:19093,PLAINTEXT://broker4:19094"
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "PLAINTEXT://broker1:19091,PLAINTEXT://broker2:19092,PLAINTEXT://broker3:19093"
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC: __schemas
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC_REPLICATION_FACTOR: 1
      SCHEMA_REGISTRY_KAFKASTORE_TIMEOUT_MS: 15000
    depends_on: [broker1, broker2, broker3]

  kafka-manager:
    image: dylanmei/kafka-manager:2.0.0.2
    ports:
    - 9000:9000
    environment:
      ZK_HOSTS: zookeeper:2181
      JMX_PORT: 7000
    depends_on: [zookeeper]
