/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package pkemeter

import kotlin.test.Test
import kotlin.test.assertTrue

class SimpleTxnMainTest {
    @Test fun nop() {
        assertTrue(true)
    }
}
