#!/usr/bin/env bash

gradle clean assemble
java \
  -Dconfig.file=./src/main/resources/application-simple.conf \
  -Dcom.sun.management.jmxremote.ssl=false \
  -Dcom.sun.management.jmxremote.authenticate=false \
  -Dcom.sun.management.jmxremote=true \
  -Dcom.sun.management.jmxremote.port=1099 \
  -Djava.rmi.server.hostname=127.0.0.1 \
  -cp build/libs/pkemeter-all.jar pkemeter.SimpleMain
